# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Source\miniprojects\part1\StudyingPyQt\mainapp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frm(object):
    def setupUi(self, Frm):
        Frm.setObjectName("Frm")
        Frm.resize(515, 305)
        self.lblMessage = QtWidgets.QLabel(Frm)
        self.lblMessage.setGeometry(QtCore.QRect(20, 10, 291, 21))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        self.lblMessage.setFont(font)
        self.lblMessage.setObjectName("lblMessage")
        self.btnOk = QtWidgets.QPushButton(Frm)
        self.btnOk.setGeometry(QtCore.QRect(400, 260, 100, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOk.sizePolicy().hasHeightForWidth())
        self.btnOk.setSizePolicy(sizePolicy)
        self.btnOk.setMinimumSize(QtCore.QSize(100, 30))
        self.btnOk.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        self.btnOk.setFont(font)
        self.btnOk.setObjectName("btnOk")
        self.btnPOP = QtWidgets.QPushButton(Frm)
        self.btnPOP.setGeometry(QtCore.QRect(290, 260, 100, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPOP.sizePolicy().hasHeightForWidth())
        self.btnPOP.setSizePolicy(sizePolicy)
        self.btnPOP.setMinimumSize(QtCore.QSize(100, 30))
        self.btnPOP.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        self.btnPOP.setFont(font)
        self.btnPOP.setObjectName("btnPOP")

        self.retranslateUi(Frm)
        QtCore.QMetaObject.connectSlotsByName(Frm)

    def retranslateUi(self, Frm):
        _translate = QtCore.QCoreApplication.translate
        Frm.setWindowTitle(_translate("Frm", "메인앱"))
        self.lblMessage.setText(_translate("Frm", "메시지:"))
        self.btnOk.setText(_translate("Frm", "Ok"))
        self.btnPOP.setText(_translate("Frm", "POP UP"))
