# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Source\miniprojects\part1\StudyPython\qrcodeApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(320, 370)
        Form.setMaximumSize(QtCore.QSize(320, 16777215))
        self.lblQrCode = QtWidgets.QLabel(Form)
        self.lblQrCode.setGeometry(QtCore.QRect(10, 10, 301, 271))
        self.lblQrCode.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lblQrCode.setText("")
        self.lblQrCode.setObjectName("lblQrCode")
        self.txtQrData = QtWidgets.QLineEdit(Form)
        self.txtQrData.setGeometry(QtCore.QRect(10, 290, 301, 20))
        self.txtQrData.setObjectName("txtQrData")
        self.btnQrGen = QtWidgets.QPushButton(Form)
        self.btnQrGen.setGeometry(QtCore.QRect(230, 320, 81, 31))
        self.btnQrGen.setObjectName("btnQrGen")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "QRCODE App"))
        self.btnQrGen.setText(_translate("Form", "Generator"))
